version: '3'
networks:
  ice:
    driver: bridge
    ipam:
        config:
        - subnet: 10.1.1.0/24

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:2024.03.2
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.2
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80/tcp'
      - '67:67/udp'
    environment:
      TZ: 'Europe/Vienna'
      WEBPASSWORD: '${PIHOLE_PASSWORD}'
      PIHOLE_DNS_: '10.1.1.3#53'
      DHCP_ACTIVE: true
      DHCP_START: 192.168.86.80
      DHCP_END: 192.168.86.250
      DHCP_ROUTER: 192.168.86.1
      PIHOLE_DOMAIN: 'home'
    volumes:
      - '${HOST_ROOT}/pihole/:/etc/pihole/'
      - '${HOST_ROOT}/dnsmasq/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    hostname: unbound
    image: klutchell/unbound:1.19.3
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.3
    ports:
      - 5053:53
    volumes:
      - ${HOST_ROOT}/unbound/custom.conf.d/:/etc/unbound/custom.conf.d/
      - ${HOST_ROOT}/unbound/unbound.conf/:/etc/unbound/unbound.conf
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.51.2
    logging:
      driver: journald
    volumes:
      - ${HOST_ROOT}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      ice:
        ipv4_address: 10.1.1.4
    ports:
      - 9090:9090
    depends_on:
      - node-exporter
      - pihole-exporter

  node-exporter:
    container_name: node-exporter
    hostname: node-exporter
    image: prom/node-exporter:v1.7.0
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.5
    ports:
      - 9100:9100
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:10.4.2
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.6
    ports:
      - 3000:3000
    user: '$UID:$GID'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ${HOST_ROOT}/grafana/data:/var/lib/grafana
      - ${HOST_ROOT}/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - loki
      - prometheus

  caddy:
    container_name: caddy
    hostname: caddy
    image: caddy:2.7.6
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.7
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: 'Europe/Vienna'
    volumes:
      - '${HOST_ROOT}/caddy/index.html:/usr/share/caddy/index.html'
      - '${HOST_ROOT}/caddy/data:/data'
      - '${HOST_ROOT}/caddy/Caddyfile:/etc/caddy/Caddyfile'
    restart: unless-stopped

  pihole-exporter:
    container_name: pihole-exporter
    hostname: pihole-exporter
    image: ekofr/pihole-exporter:v0.4.0
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.8
    ports:
      - 9617:9617
    environment:
      PORT: 9617
      PIHOLE_HOSTNAME: pihole
      PIHOLE_PASSWORD: ${PIHOLE_PASSWORD}
    depends_on:
      - pihole

  diun:
    container_name: diun
    hostname: diun
    image: crazymax/diun:4.28
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.9
    command: serve
    volumes:
      - '${HOST_ROOT}/diun/data:/data'
      - '${HOST_ROOT}/diun/diun.yml:/config/diun.yml'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: 'Europe/Vienna'
      LOG_LEVEL: 'info'
      CONFIG: '/config/diun.yml'
      DIUN_NOTIF_DISCORD_WEBHOOKURL: '${DISCORD_WEBHOOKURL}'
      DIUN_NOTIF_DISCORD_RENDERFIELDS: true
      DIUN_NOTIF_DISCORD_TIMEOUT: '10s'
      DIUN_NOTIF_DISCORD_TEMPLATEBODY: 'Docker tag {{ .Entry.Image }} has been released.'
    labels:
      - 'diun.enable=true'
    restart: always
    depends_on:
      - loki
      - pihole
      - unbound
      - pihole-exporter
      - grafana
      - caddy
      - node-exporter
      - prometheus

  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:2.9.4
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.10
    ports:
      - 3100:3100
    volumes:
      - '${HOST_ROOT}/loki/local-config.yaml:/etc/loki/local-config.yaml'
    command: -config.file=/etc/loki/local-config.yaml -log.level=warn

  promtail:
    container_name: promtail
    hostname: promtail
    image: grafana/promtail:2.9.4
    logging:
      driver: journald
    networks:
      ice:
        ipv4_address: 10.1.1.11
    ports:
      - 9080:9080
    volumes:
      - /var/log:/var/log
      - /var/lib:/var/lib
      - '${HOST_ROOT}/promtail/config.yml:/etc/promtail/config.yml'
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
